env:
    name: cosine_varying
    reward_bound: 1
    T: 10000
    N: 100
    d: 10
    frequency: 3
    amplitude: 0.8
    sigma: 0.1
alg:
    name: opkb
    kernel:
        name: rbf
        length_scale: 1
    gamma: 100
    mixture_probability: 0.2
    e_scale: 0.01
    g_scale: 0.05
    beta_scale: 50
    mu_scale: 0.2
    tol: 1.e-4
    change_detection: True
    epsilon_scale: 0.005
