env:
    name: cosine_varying
    reward_bound: 1
    mean_reward_bound: 0.8
    T: 10000
    N: 100
    d: 10
    frequency: 3
    amplitude: 0.8
    sigma: 0.1
alg:
    name: gpucb_discount
    kernel:
        name: rbf
        length_scale: 0.2
    lambda: 0.01
    beta_scale: 0.5
    eta: 0.9996
    ucb: chowdury2017
    tol: 1.e-4
