env:
    name: cosine_varying
    reward_bound: 1
    T: 10000
    N: 100
    d: 10
    frequency: 3
    amplitude: 0.8
    sigma: 0.1
alg:
    name: gpucb
    kernel:
        name: rbf
        length_scale: 0.2
    window: 2000
    lambda: 20
    v: 0.01
    tol: 1.e-4
