env:
    name: cosine
    T: 10000
    N: 256
    d: 8
    reward_bound: 1
    mean_reward_bound: 0.8
    amplitude: 0.8
    sigma: 0.1
alg:
    name: opkb
    kernel:
        name: rbf
        length_scale: 0.2
    gamma: 100
    mixture_probability: 0.2
    e_scale: 0.01
    g_scale: 0.05
    beta_scale: 50
    mu_scale: 0.2
    tol: 1.e-4
    change_detection: False
