env:
    name: cosine
    T: 10000
    N: 256
    d: 8
    reward_bound: 1
    mean_reward_bound: 0.8
    amplitude: 0.8
    sigma: 0.1
alg:
    name: gpucb
    kernel:
        name: rbf
        length_scale: 0.2
    window: 0
    lambda: 20
    v: 0.01
    tol: 1.e-4
