env:
    name: switching
    switch_time:
        - 3000
    reward_scale: 1
    reward_bound: 1
    random_reward: False
    T: 10000
    N: 100
    sigma: 0.1
    mean_reward_bound: 0.8
    env:
        name: kernel
        kernel:
            name: rbf
            length_scale: 0.2
        N: 100
        d: 10
        mean_reward_bound: 0.8
        sigma: 0.1
        T: 10000
alg:
    name: opnn
    m: 2048
    L: 3
    gamma: 100
    mixture_probability: 0.2
    e_scale: 0.005
    g_scale: 0.1
    beta_scale: 50
    mu_scale: 0.2
    tol: 1.e-4
    J: 100
    lambda: 10
    batch_size: 10000
    optimizer: sgd
    eta: 1.e-8
    change_detection: True
    prob_scale: 1.0
    epsilon_scale: 0.02
