env:
    name: switching
    switch_time:
        - 1500
        - 5000
    T: 10000
    N: 100
    reward_bound: 1
    random_reward: False
    first_hard_switch: True
    mean_reward_bound: 0.8
    sigma: 0.1
    env:
        name: kernel
        kernel:
            name: rbf
            length_scale: 0.2
        N: 100
        d: 10
        mean_reward_bound: 0.8
        sigma: 0.1
        T: 10000
alg:
    name: gpucb_discount
    kernel:
        name: rbf
        length_scale: 0.2
    lambda: 0.01
    beta_scale: 0.5
    eta: 0.9996
    ucb: chowdury2017
    tol: 1.e-4
